### ISSUE TITLE
All files are uploaded with the mimeType application/octet-stream

### ISSUE THREAD

**Issue by UltraL0rd** [uploadcare/uploadcare-java#14]
Line 76 & 78 call FileBody and ByteArrayBody which both set their mimeType's to "application/octet-stream". Both these Classes allow for mimeType to be set, they just need to be passed in.

**Comment by raphaelnew** [comment]
@UltraL0rd This issue has been fixed in [v3.3.0](https://github.com/uploadcare/uploadcare-java/releases/tag/v3.3.0)
