### ISSUE TITLE
Upload from InputStream

### ISSUE THREAD

**Issue by IvanDelsinne** [uploadcare/uploadcare-java#16]
I'm building a website using Spark, and I receive image files through an input stream.

If possible, I'd like to avoid storing the stream into a file, then using the FileUpload class to upload it, and directly use the InputStream as data source for the image.

**Comment by dmitry-mukhin** [comment]
[this](https://github.com/uploadcare/uploadcare-java/blob/master/src/main/java/com/uploadcare/upload/FileUploader.java#L52) should be able to help, right?

**Comment by IvanDelsinne** [comment]
By providing the entire image as a byte array ?

The issue I find with that is that I need to load the entire image in memory while uploading, which is not acceptable for a server-side system.

I'll take a look into the apache http lib to see if I can manage to make an edit to have an inputStream as multipart source.

**Comment by dmitry-mukhin** [comment]
closed by #17 and #18
