### ISSUE TITLE
Using UC3.2.0, the part-based upload triggers an invalid request error

### ISSUE THREAD

**Issue by Arteneko** [uploadcare/uploadcare-java#19]
The triggered exception is `com.uploadcare.exceptions.UploadcareInvalidRequestException: Request does not contain files`

My guess is that the code is missing a file-field declaration.

**Comment by dmitry-mukhin** [comment]
Can you provide stacktrace and steps to reproduce the issue?

**Comment by IvanDelsinne** [comment]
## Stack-trace

```
[qtp1300801804-17] ERROR spark.http.matching.GeneralError - 
com.uploadcare.exceptions.UploadcareInvalidRequestException: Request does not contain files.
	at com.uploadcare.api.RequestHelper.checkResponseStatus(RequestHelper.java:249)
	at com.uploadcare.api.RequestHelper.executeQuery(RequestHelper.java:124)
	at com.uploadcare.upload.FileUploader.upload(FileUploader.java:95)
	at org.artemix.laurasgallery.api.uploadcare.Uploadcare.upload(Uploadcare.java:26)
```

## Steps to reproduce

Use the following method, passing an InputStream.

In the trigger context, the InputStream was obtained from a SparkJava Request part object (see second snippet below).

```java
    public UUID upload(InputStream stream, String filename) throws UploadFailureException, IOException {
        Uploader uploader = new FileUploader(client, stream, filename);

        return UUID.fromString(uploader.upload().save().getFileId());
    }
```

```java
Part imageFile = req.raw().getPart("image");
```

**Comment by baileyatwork** [comment]
I'm running into this exact issue. Any updates?

**Comment by rsedykh** [comment]
Hi @baileyatwork. We're planning to update Java client before mid-summer. All issues will be fixed and the latest API version will be supported!

**Comment by rsedykh** [comment]
@baileyatwork actually, we'll take a look into it in a few days!

**Comment by baileyatwork** [comment]
👍 Thanks, @rsedykh.

**Comment by raphaelnew** [comment]
@baileyatwork library has been updated to [v3.3.0](https://github.com/uploadcare/uploadcare-java/releases/tag/v3.3.0). This issue should be fixed.
