### ISSUE TITLE
migrate to API v0.5

### ISSUE THREAD

**Issue by HassenHichri** [uploadcare/uploadcare-java#21]
Hello,

as mentioned here https://uploadcare.com/docs/versioning/#rest all REST API versions prior to v0.5 will be retired. This java Client is using v0.4, right?
If that's the case is there a new version of this client coming on September 1st?

Thank you 😊

**Comment by dmitry-mukhin** [comment]
There will not be a version supporting API 0.5 on 1st September, but we won't switch it off untill we have active clients using it.
We'll contact each of them individually via email.

**Comment by dmitry-mukhin** [comment]
Feel free to send a PR to speed things up)

**Comment by HassenHichri** [comment]
@dmitry-mukhin Thank you for your answer and all the library integrations. In my team, we are using this java client as well as the JS library and the REST API. I will create a PR to support v0.5.
Please bear with me as I'm not myself a java developer and this will be my first PR ever 😅

**Comment by raphaelnew** [comment]
@HassenHichri library has been updated to [v3.3.0](https://github.com/uploadcare/uploadcare-java/releases/tag/v3.3.0) and is available with support of REST API v0.6
